(("default" . ((user-emacs-directory . "~/.config/emacs_default")
	       (server-name . "emacs")))
 ("doom" . ((user-emacs-directory . "~/.config/emacs_doom")
	    (env . (("DOOMDIR" . "~/.config/emacs_doom_config")))
	    (straight-p . t)
	    (server-name . "doom")))
 ("spacemacs" . ((user-emacs-directory . "~/.config/emacs_spacemacs")
		 (env . (("SPACEMACSDIR" . "~/.config/emacs_spacemacs_config")))
		 (server-name . "spacemacs"))))
